### ISSUE TITLE
Does not work on case-sensitive file systems

### ISSUE THREAD

**Issue by alexkamp** [gbaldeck/snabbdom-kotlin#2]
Right now, this project does not work on case-sensitive file systems. The fix is merged already:

https://github.com/gbaldeck/snabbdom-kotlin/commit/ee51dd3adfcbfb89c4c44f56a5dc20cfec5eab5d

However, there was no release since then, so the version on https://dl.bintray.com/gbaldeck/kotlin still does not work in Linux. 

Would it be possible to do a new release?

**Comment by gbaldeck** [comment]
Yes, I'll let you know when it's up.

**Comment by gbaldeck** [comment]
The new version is available on Bintray. Its version is 0.1.1 and it was built with Kotlin 1.1.50, so I would recommend updating your Kotlin version to at least that.

**Comment by alexkamp** [comment]
Thanks!
