### ISSUE TITLE
Upgrade Kotlin to 1.4.0-rc

### ISSUE THREAD

**Issue by rjaros** [gbaldeck/snabbdom-kotlin#4]
Hello,

First of all thanks for your work on this project :-)

I've created a PR (#3) with some major changes and cleanups. Please review and let me know if you still want to maintain this project. Snabbdom-kotlin is an important component for my KVision framework, so I need to keep it updated.

I've converted it to Kotlin Gradle DSL, refreshed dependencies and configured publication to bintray. To publish new artifacts you just need to call:
`./gradlew -Pprod=true publish -Pbuser=USER -Pbkey=KEY`

I would be very grateful if you could publish artifacts for Kotlin 1.4.0-rc. If you have any other comments please let me know.

**Comment by gbaldeck** [comment]
Merged
